# Generated by Django 3.2.18 on 2023-09-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass_upload', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock_keeping_unit',
        ),
    ]
