# Generated by Django 3.2.18 on 2023-09-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass_upload', '0003_stock_keeping_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stgproduct',
            name='free_del_amount_limit',
        ),
    ]
