# Generated by Django 3.2.18 on 2023-09-24 06:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currier_type', models.CharField(blank=True, max_length=100, null=True)),
                ('min_weight_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('max_weight_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('buyer_shipping_fees', models.FloatField(blank=True, default=0, null=True)),
                ('seller_shipping_fees', models.FloatField(blank=True, default=0, null=True)),
                ('currier_service_ship_fees', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_content', models.CharField(blank=True, max_length=200, null=True)),
                ('parcel_value', models.FloatField(blank=True, default=0, null=True)),
                ('weight_kg', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_company', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_alt_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_email', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_company', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_alt_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_email', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_company', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_courier_company', models.CharField(blank=True, max_length=100, null=True)),
                ('sms', models.BooleanField(blank=True, default=False, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('amt_paid_by_customer', models.FloatField(blank=True, default=0, null=True)),
                ('items_amount', models.FloatField(blank=True, default=0, null=True)),
                ('shipchargepaid_by_cust', models.FloatField(blank=True, default=0, null=True)),
                ('shipchargepaid_by_vendor', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_ordered', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Return_Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_content', models.CharField(blank=True, max_length=200, null=True)),
                ('parcel_value', models.FloatField(blank=True, default=0, null=True)),
                ('weight_kg', models.CharField(blank=True, max_length=100, null=True)),
                ('return_pickup_date', models.DateField(blank=True, null=True)),
                ('returnback_pickup_date', models.DateField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_company', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_alt_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_email', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_company', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_alt_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_email', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_company', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_courier_company', models.CharField(blank=True, max_length=100, null=True)),
                ('sms', models.BooleanField(blank=True, default=False, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('amt_paid_by_customer', models.FloatField(blank=True, default=0, null=True)),
                ('items_amount', models.FloatField(blank=True, default=0, null=True)),
                ('shipchargepaid_by_cust', models.FloatField(blank=True, default=0, null=True)),
                ('shipchargepaid_by_vendor', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_ordered', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
