# Generated by Django 3.2.18 on 2023-09-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='being_delivered',
            new_name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='being_delivered',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='message',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='received',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='refund_processed',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total_product_amt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Packed', 'Packed'), ('ReadyToShip', 'ReadyToShip'), ('PickedUpToDeliver', 'PickedUpToDeliver'), ('Completed', 'Completed'), ('Delivered', 'Delivered'), ('Cancelled Order', 'Cancelled Order'), ('Return/Refund', 'Return/Refund')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Packed', 'Packed'), ('ReadyToShip', 'ReadyToShip'), ('PickedUpToDeliver', 'PickedUpToDeliver'), ('Completed', 'Completed'), ('Cancelled Item', 'Cancelled Item'), ('Cancelled Order', 'Cancelled Order'), ('Return/Refund', 'Return/Refund'), ('Return Requested', 'Return Requested')], default='New', max_length=50),
        ),
    ]
